<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'

const props = defineProps<{
  modelValue?: string
}>()

const emit = defineEmits(['update:modelValue', 'select'])

const searchQuery = ref('')
const activeCategory = ref('recent')

// Emoji Data Structure
interface Emoji {
  char: string
  name: string
}

interface Category {
  id: string
  name: string
  icon: string
  emojis: Emoji[]
}

const recentEmojis = ref<Emoji[]>([])

// Curated list of emojis with searchable names
const emojiCategories: Category[] = [
  {
    id: 'faces',
    name: 'Faces & Emotion',
    icon: 'i-lucide-smile',
    emojis: [
      { char: '😀', name: 'grinning face' },
      { char: '😃', name: 'grinning face with big eyes' },
      { char: '😄', name: 'grinning face with smiling eyes' },
      { char: '😁', name: 'beaming face with smiling eyes' },
      { char: '😆', name: 'grinning squinting face' },
      { char: '😅', name: 'grinning face with sweat' },
      { char: '🤣', name: 'rolling on the floor laughing' },
      { char: '😂', name: 'face with tears of joy' },
      { char: '🙂', name: 'slightly smiling face' },
      { char: '🙃', name: 'upside-down face' },
      { char: '😉', name: 'winking face' },
      { char: '😊', name: 'smiling face with smiling eyes' },
      { char: '😇', name: 'smiling face with halo' },
      { char: '🥰', name: 'smiling face with hearts' },
      { char: '😍', name: 'smiling face with heart-eyes' },
      { char: '🤩', name: 'star-struck' },
      { char: '😘', name: 'face blowing a kiss' },
      { char: '😗', name: 'kissing face' },
      { char: '😚', name: 'kissing face with closed eyes' },
      { char: '😙', name: 'kissing face with smiling eyes' },
      { char: '😋', name: 'face savoring food' },
      { char: '😛', name: 'face with tongue' },
      { char: '😜', name: 'winking face with tongue' },
      { char: '🤪', name: 'zany face' },
      { char: '😝', name: 'squinting face with tongue' },
      { char: '🤑', name: 'money-mouth face' },
      { char: '🤗', name: 'hugging face' },
      { char: '🤭', name: 'face with hand over mouth' },
      { char: '🤫', name: 'shushing face' },
      { char: '🤔', name: 'thinking face' },
      { char: '🤐', name: 'zipper-mouth face' },
      { char: '🤨', name: 'face with raised eyebrow' },
      { char: '😐', name: 'neutral face' },
      { char: '😑', name: 'expressionless face' },
      { char: '😶', name: 'face without mouth' },
      { char: '😏', name: 'smirking face' },
      { char: '😒', name: 'unamused face' },
      { char: '🙄', name: 'face with rolling eyes' },
      { char: '😬', name: 'grimacing face' },
      { char: '🤥', name: 'lying face' },
      { char: '😌', name: 'relieved face' },
      { char: '😔', name: 'pensive face' },
      { char: '😪', name: 'sleepy face' },
      { char: '🤤', name: 'drooling face' },
      { char: '😴', name: 'sleeping face' },
      { char: '😷', name: 'face with medical mask' },
      { char: '🤒', name: 'face with thermometer' },
      { char: '🤕', name: 'face with head-bandage' },
      { char: '🤢', name: 'nauseated face' },
      { char: '🤮', name: 'face vomiting' },
      { char: '🤧', name: 'sneezing face' },
      { char: '🥵', name: 'hot face' },
      { char: '🥶', name: 'cold face' },
      { char: '🥴', name: 'woozy face' },
      { char: '😵', name: 'dizzy face' },
      { char: '🤯', name: 'exploding head' },
      { char: '🤠', name: 'cowboy hat face' },
      { char: '🥳', name: 'partying face' },
      { char: '😎', name: 'smiling face with sunglasses' },
      { char: '🤓', name: 'nerd face' },
      { char: '🧐', name: 'face with monocle' },
      { char: '😕', name: 'confused face' },
      { char: '😟', name: 'worried face' },
      { char: '🙁', name: 'slightly frowning face' },
      { char: '😮', name: 'face with open mouth' },
      { char: '😯', name: 'hushed face' },
      { char: '😲', name: 'astonished face' },
      { char: '😳', name: 'flushed face' },
      { char: '🥺', name: 'pleading face' },
      { char: '😦', name: 'frowning face with open mouth' },
      { char: '😧', name: 'anguished face' },
      { char: '😨', name: 'fearful face' },
      { char: '😰', name: 'anxious face with sweat' },
      { char: '😥', name: 'sad but relieved face' },
      { char: '😢', name: 'crying face' },
      { char: '😭', name: 'loudly crying face' },
      { char: '😱', name: 'face screaming in fear' },
      { char: '😖', name: 'confounded face' },
      { char: '😣', name: 'persevering face' },
      { char: '😞', name: 'disappointed face' },
      { char: '😓', name: 'downcast face with sweat' },
      { char: '😩', name: 'weary face' },
      { char: '😫', name: 'tired face' },
      { char: '🥱', name: 'yawning face' },
      { char: '😤', name: 'face with steam from nose' },
      { char: '😡', name: 'pouting face' },
      { char: '😠', name: 'angry face' },
      { char: '🤬', name: 'face with symbols on mouth' },
      { char: '👿', name: 'angry face with horns' },
      { char: '😈', name: 'smiling face with horns' },
      { char: '💀', name: 'skull' },
      { char: '☠️', name: 'skull and crossbones' },
      { char: '💩', name: 'pile of poo' },
      { char: '🤡', name: 'clown face' },
      { char: '👹', name: 'ogre' },
      { char: '👺', name: 'goblin' },
      { char: '👻', name: 'ghost' },
      { char: '👽', name: 'alien' },
      { char: '👾', name: 'alien monster' },
      { char: '🤖', name: 'robot' },
    ]
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: 'i-lucide-user',
    emojis: [
      { char: '👋', name: 'waving hand' },
      { char: '🤚', name: 'raised back of hand' },
      { char: '🖐️', name: 'hand with fingers splayed' },
      { char: '✋', name: 'raised hand' },
      { char: '🖖', name: 'vulcan salute' },
      { char: '👌', name: 'OK hand' },
      { char: '🤌', name: 'pinched fingers' },
      { char: '🤏', name: 'pinching hand' },
      { char: '✌️', name: 'victory hand' },
      { char: '🤞', name: 'crossed fingers' },
      { char: '🤟', name: 'love-you gesture' },
      { char: '🤘', name: 'sign of the horns' },
      { char: '🤙', name: 'call me hand' },
      { char: '👈', name: 'backhand index pointing left' },
      { char: '👉', name: 'backhand index pointing right' },
      { char: '👆', name: 'backhand index pointing up' },
      { char: '👇', name: 'backhand index pointing down' },
      { char: '☝️', name: 'index pointing up' },
      { char: '👍', name: 'thumbs up' },
      { char: '👎', name: 'thumbs down' },
      { char: '✊', name: 'raised fist' },
      { char: '👊', name: 'oncoming fist' },
      { char: '🤛', name: 'left-facing fist' },
      { char: '🤜', name: 'right-facing fist' },
      { char: '👏', name: 'clapping hands' },
      { char: '🙌', name: 'raising hands' },
      { char: '👐', name: 'open hands' },
      { char: '🤲', name: 'palms up together' },
      { char: '🤝', name: 'handshake' },
      { char: '🙏', name: 'folded hands' },
      { char: '💅', name: 'nail polish' },
      { char: '🤳', name: 'selfie' },
      { char: '💪', name: 'flexed biceps' },
    ]
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: 'i-lucide-leaf',
    emojis: [
      { char: '🐵', name: 'monkey face' },
      { char: '🐒', name: 'monkey' },
      { char: '🦍', name: 'gorilla' },
      { char: '🐶', name: 'dog face' },
      { char: '🐕', name: 'dog' },
      { char: '🐩', name: 'poodle' },
      { char: '🐺', name: 'wolf' },
      { char: '🦊', name: 'fox' },
      { char: '🦝', name: 'raccoon' },
      { char: '🐱', name: 'cat face' },
      { char: '🐈', name: 'cat' },
      { char: '🦁', name: 'lion' },
      { char: '🐯', name: 'tiger face' },
      { char: '🐅', name: 'tiger' },
      { char: '🐆', name: 'leopard' },
      { char: '🐴', name: 'horse face' },
      { char: '🐎', name: 'horse' },
      { char: '🦄', name: 'unicorn' },
      { char: '🦓', name: 'zebra' },
      { char: '🐮', name: 'cow face' },
      { char: '🐂', name: 'ox' },
      { char: '🐃', name: 'water buffalo' },
      { char: '🐄', name: 'cow' },
      { char: '🐷', name: 'pig face' },
      { char: '🐖', name: 'pig' },
      { char: '🐗', name: 'boar' },
      { char: '🐽', name: 'pig nose' },
      { char: '🐏', name: 'ram' },
      { char: '🐑', name: 'sheep' },
      { char: '🐐', name: 'goat' },
      { char: '🐪', name: 'camel' },
      { char: '🐫', name: 'two-hump camel' },
      { char: '🦙', name: 'llama' },
      { char: '🦒', name: 'giraffe' },
      { char: '🐘', name: 'elephant' },
      { char: '🦏', name: 'rhinoceros' },
      { char: '🦛', name: 'hippopotamus' },
      { char: '🐭', name: 'mouse face' },
      { char: '🐁', name: 'mouse' },
      { char: '🐀', name: 'rat' },
      { char: '🐹', name: 'hamster' },
      { char: '🐰', name: 'rabbit face' },
      { char: '🐇', name: 'rabbit' },
      { char: '🐿️', name: 'chipmunk' },
      { char: '🦔', name: 'hedgehog' },
      { char: '🦇', name: 'bat' },
      { char: '🐻', name: 'bear' },
      { char: '🐨', name: 'koala' },
      { char: '🐼', name: 'panda' },
      { char: '🦥', name: 'sloth' },
      { char: '🦦', name: 'otter' },
      { char: '🦨', name: 'skunk' },
      { char: '🦘', name: 'kangaroo' },
      { char: '🦡', name: 'badger' },
      { char: '🌵', name: 'cactus' },
      { char: '🎄', name: 'Christmas tree' },
      { char: '🌲', name: 'evergreen tree' },
      { char: '🌳', name: 'deciduous tree' },
      { char: '🌴', name: 'palm tree' },
      { char: '🌱', name: 'seedling' },
      { char: '🌿', name: 'herb' },
      { char: '☘️', name: 'shamrock' },
      { char: '🍀', name: 'four leaf clover' },
      { char: '🎍', name: 'pine decoration' },
      { char: '🎋', name: 'tanabata tree' },
      { char: '🍃', name: 'fluttering leaf' },
      { char: '🍂', name: 'fallen leaf' },
      { char: '🍁', name: 'maple leaf' },
      { char: '🍄', name: 'mushroom' },
      { char: '🐚', name: 'spiral shell' },
      { char: '🌹', name: 'rose' },
      { char: '🥀', name: 'wilted flower' },
      { char: '🌺', name: 'hibiscus' },
      { char: '🌻', name: 'sunflower' },
      { char: '🌼', name: 'blossom' },
      { char: '🌷', name: 'tulip' },
      { char: '🔥', name: 'fire' },
      { char: '💧', name: 'droplet' },
      { char: '🌊', name: 'water wave' },
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: 'i-lucide-utensils',
    emojis: [
      { char: '🍇', name: 'grapes' },
      { char: '🍈', name: 'melon' },
      { char: '🍉', name: 'watermelon' },
      { char: '🍊', name: 'tangerine' },
      { char: '🍋', name: 'lemon' },
      { char: '🍌', name: 'banana' },
      { char: '🍍', name: 'pineapple' },
      { char: '🥭', name: 'mango' },
      { char: '🍎', name: 'red apple' },
      { char: '🍏', name: 'green apple' },
      { char: '🍐', name: 'pear' },
      { char: '🍑', name: 'peach' },
      { char: '🍒', name: 'cherries' },
      { char: '🍓', name: 'strawberry' },
      { char: '🥝', name: 'kiwi fruit' },
      { char: '🍅', name: 'tomato' },
      { char: '🥥', name: 'coconut' },
      { char: '🥑', name: 'avocado' },
      { char: '🍆', name: 'eggplant' },
      { char: '🥔', name: 'potato' },
      { char: '🥕', name: 'carrot' },
      { char: '🌽', name: 'ear of corn' },
      { char: '🌶️', name: 'hot pepper' },
      { char: '🥒', name: 'cucumber' },
      { char: '🥦', name: 'broccoli' },
      { char: '🍄', name: 'mushroom' },
      { char: '🥜', name: 'peanuts' },
      { char: '🌰', name: 'chestnut' },
      { char: '🍞', name: 'bread' },
      { char: '🥐', name: 'croissant' },
      { char: '🥖', name: 'baguette bread' },
      { char: '🥨', name: 'pretzel' },
      { char: '🥯', name: 'bagel' },
      { char: '🥞', name: 'pancakes' },
      { char: '🧇', name: 'waffle' },
      { char: '🧀', name: 'cheese wedge' },
      { char: '🍖', name: 'meat on bone' },
      { char: '🍗', name: 'poultry leg' },
      { char: '🥩', name: 'cut of meat' },
      { char: '🥓', name: 'bacon' },
      { char: '🍔', name: 'hamburger' },
      { char: '🍟', name: 'french fries' },
      { char: '🍕', name: 'pizza' },
      { char: '🌭', name: 'hot dog' },
      { char: '🥪', name: 'sandwich' },
      { char: '🌮', name: 'taco' },
      { char: '🌯', name: 'burrito' },
      { char: '🥙', name: 'stuffed flatbread' },
      { char: '🧆', name: 'falafel' },
      { char: '🥚', name: 'egg' },
      { char: '🍳', name: 'cooking' },
      { char: '🥘', name: 'shallow pan of food' },
      { char: '🍲', name: 'pot of food' },
      { char: '🥣', name: 'bowl with spoon' },
      { char: '🥗', name: 'green salad' },
      { char: '🍿', name: 'popcorn' },
      { char: '🧈', name: 'butter' },
      { char: '🧂', name: 'salt' },
      { char: '🥫', name: 'canned food' },
      { char: '🍱', name: 'bento box' },
      { char: '🍘', name: 'rice cracker' },
      { char: '🍙', name: 'rice ball' },
      { char: '🍚', name: 'cooked rice' },
      { char: '🍛', name: 'curry rice' },
      { char: '🍜', name: 'steaming bowl' },
      { char: '🍝', name: 'spaghetti' },
      { char: '🍠', name: 'roasted sweet potato' },
      { char: '🍢', name: 'oden' },
      { char: '🍣', name: 'sushi' },
      { char: '🍤', name: 'fried shrimp' },
      { char: '🍥', name: 'fish cake with swirl' },
      { char: '🥮', name: 'moon cake' },
      { char: '🍡', name: 'dango' },
      { char: '🥟', name: 'dumpling' },
      { char: '🥠', name: 'fortune cookie' },
      { char: '🥡', name: 'takeout box' },
      { char: '🍦', name: 'soft ice cream' },
      { char: '🍧', name: 'shaved ice' },
      { char: '🍨', name: 'ice cream' },
      { char: '🍩', name: 'doughnut' },
      { char: '🍪', name: 'cookie' },
      { char: '🎂', name: 'birthday cake' },
      { char: '🍰', name: 'shortcake' },
      { char: '🧁', name: 'cupcake' },
      { char: '🥧', name: 'pie' },
      { char: '🍫', name: 'chocolate bar' },
      { char: '🍬', name: 'candy' },
      { char: '🍭', name: 'lollipop' },
      { char: '🍮', name: 'custard' },
      { char: '🍯', name: 'honey pot' },
      { char: '☕', name: 'hot beverage' },
      { char: '🍵', name: 'teacup without handle' },
      { char: '🍶', name: 'sake' },
      { char: '🍾', name: 'bottle with popping cork' },
      { char: '🍷', name: 'wine glass' },
      { char: '🍸', name: 'cocktail glass' },
      { char: '🍹', name: 'tropical drink' },
      { char: '🍺', name: 'beer mug' },
      { char: '🍻', name: 'clinking beer mugs' },
      { char: '🥂', name: 'clinking glasses' },
    ]
  },
  {
    id: 'activity',
    name: 'Activities',
    icon: 'i-lucide-dumbbell',
    emojis: [
      { char: '⚽', name: 'soccer ball' },
      { char: '🏀', name: 'basketball' },
      { char: '🏈', name: 'american football' },
      { char: '⚾', name: 'baseball' },
      { char: '🥎', name: 'softball' },
      { char: '🎾', name: 'tennis' },
      { char: '🏐', name: 'volleyball' },
      { char: '🏉', name: 'rugby football' },
      { char: '🥏', name: 'flying disc' },
      { char: '🎱', name: 'pool 8 ball' },
      { char: '🪀', name: 'yo-yo' },
      { char: '🏓', name: 'ping pong' },
      { char: '🏸', name: 'badminton' },
      { char: '🏒', name: 'ice hockey' },
      { char: '🏑', name: 'field hockey' },
      { char: '🥍', name: 'lacrosse' },
      { char: '🏏', name: 'cricket game' },
      { char: '🥅', name: 'goal net' },
      { char: '⛳', name: 'flag in hole' },
      { char: '🎣', name: 'fishing pole' },
      { char: '🤿', name: 'diving mask' },
      { char: '🥊', name: 'boxing glove' },
      { char: '🥋', name: 'martial arts uniform' },
      { char: '⛸️', name: 'ice skate' },
      { char: '🥌', name: 'curling stone' },
      { char: '🎿', name: 'skis' },
      { char: '🛷', name: 'sled' },
      { char: '🛹', name: 'skateboard' },
      { char: '🎯', name: 'bullseye' },
      { char: '🎮', name: 'video game' },
      { char: '🎰', name: 'slot machine' },
      { char: '🎨', name: 'artist palette' },
      { char: '🎪', name: 'circus tent' },
      { char: '🎭', name: 'performing arts' },
      { char: '🖼️', name: 'framed picture' },
      { char: '🧵', name: 'thread' },
      { char: '🧶', name: 'yarn' },
      { char: '🎼', name: 'musical score' },
      { char: '🎤', name: 'microphone' },
      { char: '🎧', name: 'headphone' },
      { char: '🎷', name: 'saxophone' },
      { char: '🎸', name: 'guitar' },
      { char: '🎹', name: 'musical keyboard' },
      { char: '🎺', name: 'trumpet' },
      { char: '🎻', name: 'violin' },
      { char: '🥁', name: 'drum' },
      { char: '🎬', name: 'clapper board' },
      { char: '🏹', name: 'bow and arrow' },
    ]
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: 'i-lucide-plane',
    emojis: [
      { char: '🚗', name: 'automobile' },
      { char: '🚕', name: 'taxi' },
      { char: '🚙', name: 'sport utility vehicle' },
      { char: '🚌', name: 'bus' },
      { char: '🚎', name: 'trolleybus' },
      { char: '🏎️', name: 'racing car' },
      { char: '🚓', name: 'police car' },
      { char: '🚑', name: 'ambulance' },
      { char: '🚒', name: 'fire engine' },
      { char: '🚐', name: 'minibus' },
      { char: '🚚', name: 'delivery truck' },
      { char: '🚛', name: 'articulated lorry' },
      { char: '🚜', name: 'tractor' },
      { char: '🛴', name: 'kick scooter' },
      { char: '🚲', name: 'bicycle' },
      { char: '🛵', name: 'motor scooter' },
      { char: '🏍️', name: 'motorcycle' },
      { char: '🚨', name: 'police car light' },
      { char: '🚔', name: 'oncoming police car' },
      { char: '🚍', name: 'oncoming bus' },
      { char: '🚘', name: 'oncoming automobile' },
      { char: '🚖', name: 'oncoming taxi' },
      { char: '🚡', name: 'aerial tramway' },
      { char: '🚠', name: 'mountain cableway' },
      { char: '🚟', name: 'suspension railway' },
      { char: '🚃', name: 'railway car' },
      { char: '🚋', name: 'tram car' },
      { char: '🚆', name: 'train' },
      { char: '🚄', name: 'high-speed train' },
      { char: '🚅', name: 'bullet train' },
      { char: '🚈', name: 'light rail' },
      { char: '🚂', name: 'locomotive' },
      { char: '🚆', name: 'train' },
      { char: '🚇', name: 'metro' },
      { char: '🚝', name: 'monorail' },
      { char: '✈️', name: 'airplane' },
      { char: '🛫', name: 'airplane departure' },
      { char: '🛬', name: 'airplane arrival' },
      { char: '🚀', name: 'rocket' },
      { char: '🛸', name: 'flying saucer' },
      { char: '🏩', name: 'love hotel' },
      { char: '🏯', name: 'Japanese castle' },
      { char: '🏰', name: 'castle' },
      { char: '🏟️', name: 'stadium' },
      { char: '🗽', name: 'Statue of Liberty' },
      { char: '🗼', name: 'Tokyo tower' },
      { char: '🏔️', name: 'snow-capped mountain' },
      { char: '🏖️', name: 'beach with umbrella' },
      { char: '🏝️', name: 'desert island' },
      { char: '🏜️', name: 'desert' },
      { char: '🌋', name: 'volcano' },
    ]
  },
  {
    id: 'objects',
    name: 'Objects',
    icon: 'i-lucide-lightbulb',
    emojis: [
      { char: '⌚', name: 'watch' },
      { char: '📱', name: 'mobile phone' },
      { char: '📲', name: 'mobile phone with arrow' },
      { char: '💻', name: 'laptop' },
      { char: '⌨️', name: 'keyboard' },
      { char: '🖥️', name: 'desktop computer' },
      { char: '🖨️', name: 'printer' },
      { char: '🖱️', name: 'computer mouse' },
      { char: '🖲️', name: 'trackball' },
      { char: '🕹️', name: 'joystick' },
      { char: '📷', name: 'camera' },
      { char: '📸', name: 'camera with flash' },
      { char: '📹', name: 'video camera' },
      { char: '📼', name: 'videocassette' },
      { char: '🔍', name: 'magnifying glass tilted left' },
      { char: '🔎', name: 'magnifying glass tilted right' },
      { char: '🕯️', name: 'candle' },
      { char: '💡', name: 'light bulb' },
      { char: '🔦', name: 'flashlight' },
      { char: '🏮', name: 'red paper lantern' },
      { char: '📔', name: 'notebook with decorative cover' },
      { char: '📕', name: 'closed book' },
      { char: '📖', name: 'open book' },
      { char: '📗', name: 'green book' },
      { char: '📘', name: 'blue book' },
      { char: 'orange_book', name: 'orange book' },
      { char: '📚', name: 'books' },
      { char: '📓', name: 'notebook' },
      { char: '📒', name: 'ledger' },
      { char: '📃', name: 'page with curl' },
      { char: '📜', name: 'scroll' },
      { char: '📄', name: 'page facing up' },
      { char: '📰', name: 'newspaper' },
      { char: '🗞️', name: 'rolled-up newspaper' },
      { char: '📑', name: 'bookmark tabs' },
      { char: '🔖', name: 'bookmark' },
      { char: '🏷️', name: 'label' },
      { char: '💰', name: 'money bag' },
      { char: '💴', name: 'yen banknote' },
      { char: '💵', name: 'dollar banknote' },
      { char: '💶', name: 'euro banknote' },
      { char: '💷', name: 'pound banknote' },
      { char: '💸', name: 'money with wings' },
      { char: '💳', name: 'credit card' },
      { char: '🧾', name: 'receipt' },
      { char: '✉️', name: 'envelope' },
      { char: '📧', name: 'e-mail' },
      { char: '📨', name: 'incoming envelope' },
      { char: '📩', name: 'envelope with arrow' },
      { char: '📤', name: 'outbox tray' },
      { char: '📥', name: 'inbox tray' },
      { char: '📦', name: 'package' },
      { char: '📫', name: 'closed mailbox with raised flag' },
      { char: '📪', name: 'closed mailbox with lowered flag' },
      { char: '📬', name: 'open mailbox with raised flag' },
      { char: '📭', name: 'open mailbox with lowered flag' },
      { char: '📮', name: 'postbox' },
      { char: '📝', name: 'memo' },
      { char: '💼', name: 'briefcase' },
      { char: '📁', name: 'file folder' },
      { char: '📂', name: 'open file folder' },
      { char: '📅', name: 'calendar' },
      { char: '📆', name: 'tear-off calendar' },
      { char: '🗒️', name: 'spiral notepad' },
      { char: '🗓️', name: 'spiral calendar' },
      { char: '📇', name: 'card index' },
      { char: '📈', name: 'chart increasing' },
      { char: '📉', name: 'chart decreasing' },
      { char: '📊', name: 'bar chart' },
      { char: '📋', name: 'clipboard' },
      { char: '📌', name: 'pushpin' },
      { char: '📍', name: 'round pushpin' },
      { char: '📎', name: 'paperclip' },
      { char: '🖇️', name: 'linked paperclips' },
      { char: '📏', name: 'straight ruler' },
      { char: '📐', name: 'triangular ruler' },
      { char: '✂️', name: 'scissors' },
      { char: '🗃️', name: 'card file box' },
      { char: '🗄️', name: 'file cabinet' },
      { char: '🗑️', name: 'wastebasket' },
      { char: '🔒', name: 'locked' },
      { char: '🔓', name: 'unlocked' },
      { char: '🔏', name: 'locked with pen' },
      { char: '🔐', name: 'locked with key' },
      { char: '🔑', name: 'key' },
      { char: '🗝️', name: 'old key' },
      { char: '🔨', name: 'hammer' },
      { char: '🪓', name: 'axe' },
      { char: '⛏️', name: 'pick' },
      { char: '⚒️', name: 'hammer and pick' },
      { char: '🛠️', name: 'hammer and wrench' },
      { char: '🗡️', name: 'dagger' },
      { char: '⚔️', name: 'crossed swords' },
      { char: '🔫', name: 'water pistol' },
      { char: '🏹', name: 'bow and arrow' },
      { char: '🛡️', name: 'shield' },
      { char: '🔧', name: 'wrench' },
      { char: '🔩', name: 'nut and bolt' },
      { char: '⚙️', name: 'gear' },
      { char: '🗜️', name: 'clamp' },
      { char: '⚖️', name: 'balance scale' },
      { char: '🦯', name: 'white cane' },
      { char: '🔗', name: 'link' },
      { char: '⛓️', name: 'chains' },
      { char: '🧰', name: 'toolbox' },
      { char: '🧲', name: 'magnet' },
      { char: '⚗️', name: 'alembic' },
      { char: '🧪', name: 'test tube' },
      { char: '🧫', name: 'petri dish' },
      { char: '🧬', name: 'dna' },
      { char: '🔬', name: 'microscope' },
      { char: '🔭', name: 'telescope' },
      { char: '📡', name: 'satellite antenna' },
      { char: '💉', name: 'syringe' },
      { char: '🩸', name: 'drop of blood' },
      { char: '💊', name: 'pill' },
      { char: '🩹', name: 'adhesive bandage' },
      { char: '🩺', name: 'stethoscope' },
      { char: '🚪', name: 'door' },
      { char: '🛏️', name: 'bed' },
      { char: '🛋️', name: 'couch and lamp' },
      { char: '🪑', name: 'chair' },
      { char: '🚽', name: 'toilet' },
      { char: '🚿', name: 'shower' },
      { char: '🛁', name: 'bathtub' },
      { char: '🪒', name: 'razor' },
      { char: '🧴', name: 'lotion bottle' },
      { char: '🧷', name: 'safety pin' },
      { char: '🧹', name: 'broom' },
      { char: '🧺', name: 'basket' },
      { char: '🧻', name: 'roll of paper' },
      { char: '🧼', name: 'soap' },
      { char: '🧽', name: 'sponge' },
      { char: '🧯', name: 'fire extinguisher' },
      { char: '🛒', name: 'shopping cart' },
    ]
  },
  {
    id: 'symbols',
    name: 'Symbols',
    icon: 'i-lucide-heart',
    emojis: [
      { char: '❤️', name: 'red heart' },
      { char: '🧡', name: 'orange heart' },
      { char: '💛', name: 'yellow heart' },
      { char: '💚', name: 'green heart' },
      { char: '💙', name: 'blue heart' },
      { char: '💜', name: 'purple heart' },
      { char: '🖤', name: 'black heart' },
      { char: '🤍', name: 'white heart' },
      { char: '🤎', name: 'brown heart' },
      { char: '💔', name: 'broken heart' },
      { char: '❣️', name: 'heart exclamation' },
      { char: '💕', name: 'two hearts' },
      { char: '💞', name: 'revolving hearts' },
      { char: '💓', name: 'beating heart' },
      { char: '💗', name: 'growing heart' },
      { char: '💖', name: 'sparkling heart' },
      { char: '💘', name: 'heart with arrow' },
      { char: '💝', name: 'heart with ribbon' },
      { char: '💟', name: 'heart decoration' },
      { char: '☮️', name: 'peace symbol' },
      { char: '✝️', name: 'latin cross' },
      { char: '☪️', name: 'star and crescent' },
      { char: '🕉️', name: 'om' },
      { char: '☸️', name: 'wheel of dharma' },
      { char: '✡️', name: 'star of david' },
      { char: '🔯', name: 'dotted six-pointed star' },
      { char: '🕎', name: 'menorah' },
      { char: '☯️', name: 'yin yang' },
      { char: '☦️', name: 'orthodox cross' },
      { char: '🛐', name: 'place of worship' },
      { char: '⛎', name: 'ophiuchus' },
      { char: '♈', name: 'aries' },
      { char: '♉', name: 'taurus' },
      { char: '♊', name: 'gemini' },
      { char: '♋', name: 'cancer' },
      { char: '♌', name: 'leo' },
      { char: '♍', name: 'virgo' },
      { char: '♎', name: 'libra' },
      { char: '♏', name: 'scorpio' },
      { char: '♐', name: 'sagittarius' },
      { char: '♑', name: 'capricorn' },
      { char: '♒', name: 'aquarius' },
      { char: '♓', name: 'pisces' },
      { char: '🆔', name: 'ID button' },
      { char: '⚛️', name: 'atom symbol' },
      { char: '🉑', name: 'Japanese “acceptable” button' },
      { char: '☢️', name: 'radioactive' },
      { char: '☣️', name: 'biohazard' },
      { char: '📴', name: 'mobile phone off' },
      { char: '📳', name: 'vibration mode' },
      { char: '🈶', name: 'Japanese “not free of charge” button' },
      { char: '🈚', name: 'Japanese “free of charge” button' },
      { char: '🈸', name: 'Japanese “application” button' },
      { char: '🈺', name: 'Japanese “open for business” button' },
      { char: '🈷️', name: 'Japanese “monthly amount” button' },
      { char: '✴️', name: 'eight-pointed star' },
      { char: '🆚', name: 'VS button' },
      { char: '💮', name: 'white flower' },
      { char: '🉐', name: 'Japanese “bargain” button' },
      { char: '㊙️', name: 'Japanese “secret” button' },
      { char: '㊗️', name: 'Japanese “congratulations” button' },
      { char: '🈴', name: 'Japanese “passing grade” button' },
      { char: '🈵', name: 'Japanese “no vacancy” button' },
      { char: '🈹', name: 'Japanese “discount” button' },
      { char: '🈲', name: 'Japanese “prohibited” button' },
      { char: '🅰️', name: 'A button (blood type)' },
      { char: '🅱️', name: 'B button (blood type)' },
      { char: '🆎', name: 'AB button (blood type)' },
      { char: '🆑', name: 'CL button' },
      { char: '🅾️', name: 'O button (blood type)' },
      { char: '🆘', name: 'SOS button' },
      { char: '❌', name: 'cross mark' },
      { char: '⭕', name: 'hollow red circle' },
      { char: '🛑', name: 'stop sign' },
      { char: '⛔', name: 'no entry' },
      { char: '📛', name: 'name badge' },
      { char: '🚫', name: 'prohibited' },
      { char: '💯', name: 'hundred points' },
      { char: '💢', name: 'anger symbol' },
      { char: '♨️', name: 'hot springs' },
      { char: '🚷', name: 'no pedestrians' },
      { char: '🚯', name: 'no littering' },
      { char: '🚳', name: 'no bicycles' },
      { char: '🚱', name: 'non-potable water' },
      { char: '🔞', name: 'no one under eighteen' },
      { char: '📵', name: 'no mobile phones' },
      { char: '🚭', name: 'no smoking' },
      { char: '❗', name: 'exclamation mark' },
      { char: '❕', name: 'white exclamation mark' },
      { char: '❓', name: 'question mark' },
      { char: '❔', name: 'white question mark' },
      { char: '‼️', name: 'double exclamation mark' },
      { char: '⁉️', name: 'exclamation question mark' },
      { char: '🔅', name: 'dim button' },
      { char: '🔆', name: 'bright button' },
      { char: '〽️', name: 'part alternation mark' },
      { char: '⚠️', name: 'warning' },
      { char: '🚸', name: 'children crossing' },
      { char: '🔱', name: 'trident emblem' },
      { char: '🔰', name: 'Japanese symbol for beginner' },
      { char: '♻️', name: 'recycling symbol' },
      { char: '✅', name: 'check mark button' },
      { char: '🈯', name: 'Japanese “reserved” button' },
      { char: '💹', name: 'chart increasing with yen' },
      { char: '❇️', name: 'sparkle' },
      { char: '✳️', name: 'eight-spoked asterisk' },
      { char: '❎', name: 'cross mark button' },
      { char: '🌐', name: 'globe with meridians' },
      { char: '💠', name: 'diamond with a dot' },
      { char: 'Ⓜ️', name: 'circled M' },
      { char: '🌀', name: 'cyclone' },
      { char: '💤', name: 'zzz' },
      { char: '🏧', name: 'ATM sign' },
      { char: '🚾', name: 'water closet' },
      { char: '♿', name: 'wheelchair symbol' },
      { char: '🅿️', name: 'P button' },
      { char: '🈳', name: 'Japanese “vacancy” button' },
    ]
  }
]

onMounted(() => {
  const recent = localStorage.getItem('nuxt4-cms-recent-emojis')
  if (recent) {
    try {
      recentEmojis.value = JSON.parse(recent)
    } catch (e) {
      console.error('Failed to parse recent emojis', e)
    }
  }

  // Set default active category to faces if no filtered search
  activeCategory.value = 'faces'
})

const filteredEmojis = computed(() => {
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase()

    // Search across all categories
    let results: Emoji[] = []
    emojiCategories.forEach(cat => {
      const matches = cat.emojis.filter(e => e.name.toLowerCase().includes(query) || e.char === query)
      results = [...results, ...matches]
    })
    return results
  }

  if (activeCategory.value === 'recent') {
    return recentEmojis.value
  }

  const category = emojiCategories.find(c => c.id === activeCategory.value)
  return category ? category.emojis : []
})

const selectEmoji = (emoji: Emoji) => {
  // Add to recent
  const newRecent = [emoji, ...recentEmojis.value.filter(e => e.char !== emoji.char)].slice(0, 30)
  recentEmojis.value = newRecent
  localStorage.setItem('nuxt4-cms-recent-emojis', JSON.stringify(newRecent))

  emit('update:modelValue', emoji.char)
  emit('select', emoji.char)
}

</script>

<template>
  <div class="flex flex-col gap-3 min-w-[300px] h-full overflow-hidden">
    <!-- Header: Tabs for Categories -->
    <div class="flex items-center gap-1 overflow-x-auto pb-2 border-b dark:border-gray-700 no-scrollbar">
      <button type="button" class="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors shrink-0"
        :class="{ 'text-primary-500 bg-primary-50 dark:bg-primary-950/30': activeCategory === 'recent' && !searchQuery }"
        @click="activeCategory = 'recent'; searchQuery = ''" title="Recently Used">
        <UIcon name="i-lucide-clock" class="w-5 h-5" />
      </button>
      <button v-for="cat in emojiCategories" :key="cat.id" type="button"
        class="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors shrink-0"
        :class="{ 'text-primary-500 bg-primary-50 dark:bg-primary-950/30': activeCategory === cat.id && !searchQuery }"
        @click="activeCategory = cat.id; searchQuery = ''" :title="cat.name">
        <UIcon :name="cat.icon" class="w-5 h-5" />
      </button>
    </div>

    <!-- Search -->
    <UInput v-model="searchQuery" :placeholder="$t('editor.enter_emoji') || 'Search emojis...'" icon="i-lucide-search"
      autofocus size="sm" />

    <!-- Grid -->
    <div class="flex-1 overflow-y-auto min-h-[250px] max-h-[300px] pr-1">
      <div v-if="filteredEmojis.length === 0" class="text-center py-8 text-gray-500 text-sm">
        No emojis found
      </div>

      <div v-else>
        <div v-if="!searchQuery && activeCategory === 'recent' && recentEmojis.length === 0"
          class="text-center py-8 text-gray-500 text-sm">
          No recently used emojis
        </div>

        <div class="grid grid-cols-8 gap-1">
          <button v-for="emoji in filteredEmojis" :key="emoji.char" type="button"
            class="flex items-center justify-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800 text-xl transition-colors aspect-square"
            @click="selectEmoji(emoji)" :title="emoji.name">
            {{ emoji.char }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.no-scrollbar::-webkit-scrollbar {
  display: none;
}

.no-scrollbar {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
</style>
